name: SimpleCoins
main: MCATECH\SimpleCoins\SimpleCoins
version: 1.14.3
api: [3.0.0, 3.11.0, 3.11.6]
load: POSTWORLD
description: A simpler Economy Plugin. More details about this plugin are found in the ReadMe.md
author: MCATECH
commands:
 rarecoins:
  default: true
  description: 'Check for rarecoins'
 setcoins:
  default: op
  description: 'Set a players coin balance'
 remcoins:
  default: op
  description: 'Remove coins from a player'
permissions:
 coin.command:
  default: true